sudo: required
services:
  - docker

before_install:
  - docker build -t rzangdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rzangdocker/react-test npm test -- -- coverage

after_success: 
  - docker build -t rzangdocker/multi-client ./client
  - docker build -t rzangdocker/multi-nginx ./nginx
  - docker build -t rzangdocker/mutli-server ./server
  - docker build -t rzangdocker/mutli-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rzangdocker/multi-client
  - docker push rzangdocker/multi-nginx
  - docker push rzangdocker/multi-server
  - docker push rzangdocker/multi-worker
  